"""create_category_table

Revision ID: 35f178b4cb4a
Revises: 
Create Date: 2023-02-01 22:08:40.105135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f178b4cb4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('category_shard', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('children', sa.Boolean(), nullable=True),
    sa.Column('displayed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Category')
    # ### end Alembic commands ###
