"""create_category_table

Revision ID: be0c1ace52ed
Revises: 
Create Date: 2023-02-03 00:43:56.554616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0c1ace52ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('category_shard', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('children', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Category')
    # ### end Alembic commands ###
