"""comment

Revision ID: e35ddff5d066
Revises: a1a810d2f526
Create Date: 2023-02-15 22:29:49.567413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35ddff5d066'
down_revision = 'a1a810d2f526'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
